nodeLinker: pnpm
yarnPath: .yarn/releases/yarn-4.5.1.cjs
packageExtensions:
  "@module-federation/enhanced@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@module-federation/manifest@*":
    peerDependencies:
      "typescript": "*"
  "@nx/eslint-plugin@*":
    peerDependencies:
      "@types/node": "*"
      "eslint": "*"
      "nx": "*"
      "typescript": "*"
  "@nx/eslint@*":
    peerDependencies:
      "@types/node": "*"
      "nx": "*"
  "@nx/jest@*":
    peerDependencies:
      "@types/node": "*"
      "nx": "*"
      "typescript": "*"
  "@nx/js@*":
    peerDependencies:
      "@types/node": "*"
      "nx": "*"
      "typescript": "*"
  "@nx/nest@*":
    peerDependencies:
      "@types/node": "*"
      "eslint": "*"
      "nx": "*"
      "typescript": "*"
  "@nx/node@*":
    peerDependencies:
      "@types/node": "*"
      "nx": "*"
      "typescript": "*"
      "eslint": "*"
  "@nx/web@*":
    peerDependencies:
      "@types/node": "*"
      "nx": "*"
      "typescript": "*"
  "@nx/webpack@*":
    peerDependencies:
      "@types/node": "*"
      "nx": "*"
      "typescript": "*"
      "react": "*"
      "react-dom": "*"
  "@swc-node/register@*":
    peerDependencies:
      "@swc/types": "*"
  "@typescript-eslint/type-utils@*":
    peerDependencies:
      "eslint": "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      "typescript": "*"
  "typescript-eslint@*":
    peerDependencies:
      "eslint": "*"

